# -*- coding: utf-8 -*-
"""P3_stego_avanzado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cF6BOm4WXf0M5APesrVGXPlhudX4OycJ

# PRÁCTICA	2 — Esteganografía	Avanzada:	Distribución Aleatoria	y	Cifrado
"""

# ================================================================
# PRACTICA 2 — Esteganografía en BMP 24 bpp
# - Carriers SIN padding (B, G, R)
# - PRNG determinista derivado de contraseña (permutación)
# - Cifrado XOR con clave de SHA-256 (modo contador, docente)
# - Encabezado 32 bits LE (longitud) + mensaje cifrado
# - χ² de LSBs y PSNR opcional
# ================================================================

import struct, math, hashlib, random
from typing import Tuple, List

# -------------------------------
# Utilidades BMP (24 bpp, BI_RGB)
# -------------------------------
def leer_bmp(path: str) -> Tuple[bytearray, bytearray, int, int, int, int]:
    """
    Lee un BMP y retorna:
      header (bytes antes de los datos de píxel),
      pixels (datos de píxel),
      width, height (int),
      bpp (bits por pixel),
      row_size (bytes por fila, con padding a múltiplos de 4)

    Valida 'BM', 24 bpp y sin compresión (BI_RGB).
    """
    with open(path, 'rb') as f:
        data = bytearray(f.read())

    if data[0:2] != b'BM':
        raise ValueError("No es un BMP válido (falta firma 'BM').")

    pixel_offset = struct.unpack_from('<I', data, 10)[0]
    width = struct.unpack_from('<i', data, 18)[0]
    height = struct.unpack_from('<i', data, 22)[0]
    bpp = struct.unpack_from('<H', data, 28)[0]
    compression = struct.unpack_from('<I', data, 30)[0]

    if bpp != 24:
        raise ValueError(f"Se requiere BMP de 24 bpp. Este es {bpp} bpp.")
    if compression != 0:
        raise ValueError("Se requiere BMP sin compresión (BI_RGB).")

    row_size = ((abs(width) * 3 + 3) // 4) * 4
    header = data[:pixel_offset]
    pixels = data[pixel_offset:]

    expected_pixels = row_size * abs(height)
    if len(pixels) < expected_pixels:
        raise ValueError("BMP truncado o corrupto (pixeles insuficientes).")

    return header, pixels, width, height, bpp, row_size


def guardar_bmp(path: str, header: bytearray, pixels: bytearray):
    with open(path, 'wb') as f:
        f.write(header)
        f.write(pixels)


def indices_carrier(width: int, height: int, row_size: int) -> List[int]:
    """
    Retorna índices de bytes de color B,G,R por fila (excluye padding).
    """
    h = abs(height)
    carriers = []
    row_payload = width * 3  # B,G,R por fila
    base = 0
    for _ in range(h):
        carriers.extend(range(base, base + row_payload))
        base += row_size
    return carriers


# -------------------------------
# Conversión bits <-> bytes (MSB)
# -------------------------------
def _to_bits_be(data: bytes) -> list:
    """bytes -> bits (MSB→LSB por byte)"""
    bits = []
    for byte in data:
        for i in range(7, -1, -1):
            bits.append((byte >> i) & 1)
    return bits

def _bits_to_bytes_be(bits: list) -> bytes:
    """bits (MSB→LSB por byte) -> bytes"""
    out = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for b in bits[i:i+8]:
            byte = (byte << 1) | b
        out.append(byte)
    return bytes(out)


# -------------------------------
# PSNR (opcional)
# -------------------------------
def calcular_psnr(original_path: str, stego_path: str) -> float:
    """
    PSNR sobre bytes B,G,R (excluye padding).
    """
    _, pix_o, w, h, bpp, row_size = leer_bmp(original_path)
    _, pix_s, *_ = leer_bmp(stego_path)

    carriers = indices_carrier(w, h, row_size)
    mse = 0.0
    for idx in carriers:
        diff = int(pix_o[idx]) - int(pix_s[idx])
        mse += diff * diff
    mse /= len(carriers)

    if mse == 0:
        print("MSE=0 → PSNR=∞ (no hay diferencias).")
        return float('inf')

    psnr = 10.0 * math.log10((255 ** 2) / mse)
    print(f"MSE: {mse:.6f}")
    print(f"PSNR: {psnr:.2f} dB (≈ >40 dB suele ser imperceptible)")
    return psnr


# -------------------------------------------------
# Clave derivada + XOR (modo contador, docente)
# -------------------------------------------------
def derivar_clave(password: str, longitud: int) -> bytes:
    """
    Expansión con SHA-256 en modo contador para obtener 'longitud' bytes.
    (Docente; en sistemas reales usar KDF robusta.)
    """
    clave = b''
    contador = 0
    while len(clave) < longitud:
        bloque = hashlib.sha256(password.encode('utf-8') + struct.pack('<I', contador)).digest()
        clave += bloque
        contador += 1
    return clave[:longitud]

def cifrar_xor(mensaje: bytes, password: str) -> bytes:
    key = derivar_clave(password, len(mensaje))
    return bytes(m ^ k for m, k in zip(mensaje, key))

def descifrar_xor(cifrado: bytes, password: str) -> bytes:
    return cifrar_xor(cifrado, password)  # XOR es simétrico


# -------------------------------------------------
# PRNG determinista (permutación de carriers)
# -------------------------------------------------
def semilla_de_password(password: str) -> int:
    h = hashlib.sha256(password.encode('utf-8')).digest()
    return int.from_bytes(h[:8], 'big')  # 64 bits

def posiciones_barajadas(n_carriers: int, seed: int) -> List[int]:
    """
    Permutación estable de [0..n_carriers-1] usando 'seed'.
    El prefijo de 32 posiciones se usa para la longitud; el resto, para el mensaje.
    """
    rng = random.Random(seed)
    pos = list(range(n_carriers))
    rng.shuffle(pos)
    return pos


# -------------------------------------------------
# Esteganografía robusta (PRNG + XOR)
# -------------------------------------------------
def embed_secure(src_path: str, dst_path: str, mensaje: str, password: str):
    """
    Escribe: [32 bits LE longitud][mensaje_cifrado_xor] en LSBs de bytes B,G,R
    según una permutación pseudoaleatoria derivada de 'password'.
    """
    header, pixels, w, h, bpp, row_size = leer_bmp(src_path)
    carriers = indices_carrier(w, h, row_size)

    msg = mensaje.encode('utf-8')
    cifrado = cifrar_xor(msg, password)

    datos = struct.pack('<I', len(msg)) + cifrado
    bits = _to_bits_be(datos)

    if len(bits) > len(carriers):
        raise ValueError(f"Mensaje demasiado grande. Bits={len(bits)}, Capacidad={len(carriers)}")

    seed = semilla_de_password(password)
    perm = posiciones_barajadas(len(carriers), seed)

    pixels_mod = bytearray(pixels)
    for i, bit in enumerate(bits):
        c_idx = carriers[perm[i]]
        pixels_mod[c_idx] = (pixels_mod[c_idx] & 0xFE) | bit

    guardar_bmp(dst_path, header, pixels_mod)
    print(f"[OK] Incrustados {len(msg)} bytes (cifrados) en '{dst_path}' con PRNG+XOR.")


def extract_secure(stego_path: str, password: str) -> str:
    """
    Extrae el mensaje embebido por 'embed_secure' usando la misma contraseña.
    """
    header, pixels, w, h, bpp, row_size = leer_bmp(stego_path)
    carriers = indices_carrier(w, h, row_size)

    seed = semilla_de_password(password)
    perm = posiciones_barajadas(len(carriers), seed)

    # 1) Leer 32 bits de longitud (como 4 bytes LE)
    len_bits = [(pixels[carriers[perm[i]]] & 1) for i in range(32)]
    len_bytes = _bits_to_bytes_be(len_bits)
    msg_len = struct.unpack('<I', len_bytes)[0]

    total_bits = 32 + msg_len * 8
    if total_bits > len(perm):
        raise ValueError("La longitud indicada excede la capacidad (archivo dañado/clave incorrecta).")

    # 2) Leer bits del mensaje cifrado
    msg_bits = [(pixels[carriers[perm[i]]] & 1) for i in range(32, total_bits)]
    cifrado = _bits_to_bytes_be(msg_bits)

    # 3) Descifrar
    try:
        claro = descifrar_xor(cifrado, password).decode('utf-8')
    except UnicodeDecodeError:
        raise ValueError("No se pudo decodificar el mensaje (¿contraseña incorrecta o datos corruptos?).")
    return claro


# ------------------------------
# Análisis χ² sobre LSBs
# ------------------------------
def chi_cuadrado_lsb(path: str) -> float:
    """
    χ² de los LSBs contando 0s/1s SOLO en B,G,R (excluye padding).
    """
    header, pixels, w, h, bpp, row_size = leer_bmp(path)
    carriers = indices_carrier(w, h, row_size)
    ceros = sum(1 for idx in carriers if (pixels[idx] & 1) == 0)
    unos = len(carriers) - ceros
    esperado = len(carriers) / 2.0
    chi2 = ((ceros - esperado)**2 + (unos - esperado)**2) / (esperado if esperado != 0 else 1.0)
    print(f"LSBs=0: {ceros} | LSBs=1: {unos} | χ²= {chi2:.4f}")
    return chi2


# ------------------------------
# Conversión a BMP 24 bpp (opcional)
# ------------------------------
def convertir_a_bmp_24bpp(entrada_path: str, salida_path: str = 'imagen.bmp'):
    """
    Convierte una imagen (PNG/JPG/etc.) a BMP 24 bpp sin compresión.
    """
    try:
        from PIL import Image
        img = Image.open(entrada_path).convert('RGB')
        img.save(salida_path, format='BMP')
        print(f"Convertido '{entrada_path}' → '{salida_path}' (24 bpp).")
    except Exception as e:
        raise RuntimeError(f"No se pudo convertir '{entrada_path}' a BMP 24 bpp: {e}")



def ejecutar_practica_2(
    src_path='/content/Images/volcan.bmp',
    dst_path='/content/Images/stego_seguroVolcan.bmp',
    mensaje='Datos confidenciales de la red 10.0.1.0/24',
    clave='Telemática@2026',
    calcular_psnr_flag=True
):
    # Embed seguro
    embed_secure(src_path, dst_path, mensaje, clave)

    # Extract: clave correcta
    extraido = extract_secure(dst_path, clave)
    print("Extracción segura (correcta):", extraido)

    # Extract: clave incorrecta
    try:
        print("Extracción segura (clave incorrecta):", extract_secure(dst_path, 'claveWrong'))
    except Exception as e:
        print("Extracción segura (clave incorrecta) →", e)

    # χ²
    print("=== χ² Imagen original ===")
    chi_cuadrado_lsb(src_path)
    print("=== χ² Stego PRNG+XOR ===")
    chi_cuadrado_lsb(dst_path)

    # PSNR opcional
    if calcular_psnr_flag:
        print("=== PSNR (opcional) ===")
        calcular_psnr(src_path, dst_path)

ejecutar_practica_2();

"""# Generador de Histogramas"""

import numpy as np
import matplotlib.pyplot as plt

def mostrar_histograma_bgr(original_path: str, stego_path: str):
    _, p0, w, h, bpp, row_size = leer_bmp(original_path)
    _, p1, *_ = leer_bmp(stego_path)
    carriers = indices_carrier(w, h, row_size)

    b0 = np.array([p0[i] for i in carriers[0::3]])
    g0 = np.array([p0[i] for i in carriers[1::3]])
    r0 = np.array([p0[i] for i in carriers[2::3]])

    b1 = np.array([p1[i] for i in carriers[0::3]])
    g1 = np.array([p1[i] for i in carriers[1::3]])
    r1 = np.array([p1[i] for i in carriers[2::3]])

    fig, axs = plt.subplots(3, 2, figsize=(10, 8))
    canales = [('B', b0, b1), ('G', g0, g1), ('R', r0, r1)]

    for row, (name, o, s) in enumerate(canales):
        axs[row, 0].hist(o, bins=256, range=(0,255), color=name.lower())
        axs[row, 0].set_title(f'Original {name}')
        axs[row, 1].hist(s, bins=256, range=(0,255), color=name.lower())
        axs[row, 1].set_title(f'Stego {name}')

    plt.tight_layout()
    plt.show()

mostrar_histograma_bgr('/content/Images/volcan.bmp', '/content/Images/stego_seguroVolcan.bmp')