# -*- coding: utf-8 -*-
"""P2_lsb_stego.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112kYp3DLl9u1HHxlZpr_Ajnk77Lq9h8C

# Práctica  7 (1): Esteganografía	LSB	en	Imágenes	BMP
"""

# ================================================================
# PRACTICA 1 — Esteganografía LSB en BMP 24 bpp
# - Lectura BMP 24 bpp (sin compresión), respetando padding
# - Embed/Extract con encabezado de 32 bits (longitud)
# - PSNR sobre bytes B,G,R
# ================================================================

import struct, math
from typing import Tuple, List

# -------------------------------
# Utilidades BMP (24 bpp, BI_RGB)
# -------------------------------
def leer_bmp(path: str) -> Tuple[bytearray, bytearray, int, int, int, int]:
    """
    Lee un BMP y retorna:
      header (bytes antes de los datos de píxel),
      pixels (datos de píxel),
      width, height (int),
      bpp (bits por pixel),
      row_size (bytes por fila, con padding a múltiplos de 4)

    Valida 'BM', 24 bpp y sin compresión (BI_RGB).
    """
    with open(path, 'rb') as f:
        data = bytearray(f.read())

    # Firma 'BM'
    if data[0:2] != b'BM':
        raise ValueError("No es un archivo BMP válido (falta firma 'BM').")

    # Encabezados BMP/DIB
    pixel_offset = struct.unpack_from('<I', data, 10)[0]
    width = struct.unpack_from('<i', data, 18)[0]
    height = struct.unpack_from('<i', data, 22)[0]
    bpp = struct.unpack_from('<H', data, 28)[0]
    compression = struct.unpack_from('<I', data, 30)[0]

    if bpp != 24:
        raise ValueError(f"Se requiere BMP de 24 bpp (RGB). Este es {bpp} bpp.")
    if compression != 0:
        raise ValueError("Se requiere BMP sin compresión (BI_RGB).")

    # Tamaño de fila con padding a múltiplos de 4
    row_size = ((abs(width) * 3 + 3) // 4) * 4

    header = data[:pixel_offset]
    pixels = data[pixel_offset:]

    # Comprobación de tamaño esperado de datos
    expected_pixels = row_size * abs(height)
    if len(pixels) < expected_pixels:
        raise ValueError("El archivo BMP parece truncado o corrupto (pixeles insuficientes).")

    return header, pixels, width, height, bpp, row_size


def guardar_bmp(path: str, header: bytearray, pixels: bytearray):
    with open(path, 'wb') as f:
        f.write(header)
        f.write(pixels)


def indices_carrier(width: int, height: int, row_size: int) -> List[int]:
    """
    Retorna los índices (relativos a 'pixels') que corresponden a bytes de color B,G,R
    (excluye los bytes de padding por fila).
    """
    h = abs(height)
    carriers = []
    row_payload = width * 3  # bytes B,G,R por fila
    base = 0
    for _ in range(h):
        carriers.extend(range(base, base + row_payload))
        base += row_size
    return carriers


def capacidad_bytes(width: int, height: int) -> int:
    """Capacidad teórica con 1 LSB por canal B,G,R (≈ (W*H*3)/8 bytes)."""
    return (abs(width) * abs(height) * 3) // 8


# -------------------------------
# Conversión bits <-> bytes (MSB)
# -------------------------------
def _to_bits_be(data: bytes) -> list:
    """Convierte bytes a bits (MSB→LSB por byte)."""
    bits = []
    for byte in data:
        for i in range(7, -1, -1):
            bits.append((byte >> i) & 1)
    return bits

def _bits_to_bytes_be(bits: list) -> bytes:
    """Convierte lista de bits (MSB→LSB por byte) a bytes."""
    out = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for b in bits[i:i+8]:
            byte = (byte << 1) | b
        out.append(byte)
    return bytes(out)

def embed_lsb(src_path: str, dst_path: str, mensaje: str):
    """
    Incrusta: [32 bits longitud (LE)][mensaje UTF-8] en los LSB de bytes B,G,R
    recorriendo portadores en orden secuencial (excluye padding).
    """
    header, pixels, w, h, bpp, row_size = leer_bmp(src_path)
    carriers = indices_carrier(w, h, row_size)

    msg_bytes = mensaje.encode('utf-8')
    # 4 bytes de longitud (little-endian) + mensaje
    datos = struct.pack('<I', len(msg_bytes)) + msg_bytes
    bits = _to_bits_be(datos)

    if len(bits) > len(carriers):
        raise ValueError(f"Mensaje demasiado grande. Bits necesarios={len(bits)}, capacidad bits={len(carriers)}")

    pixels_mod = bytearray(pixels)
    for i, bit in enumerate(bits):
        pos = carriers[i]
        pixels_mod[pos] = (pixels_mod[pos] & 0xFE) | bit

    guardar_bmp(dst_path, header, pixels_mod)
    print(f"[OK] Incrustados {len(msg_bytes)} bytes en '{dst_path}' usando LSB secuencial.")


def extract_lsb(stego_path: str) -> str:
    """
    Extrae un mensaje embebido con 'embed_lsb'.
    **Corregido**: reconstruye 4 bytes de longitud desde 32 bits (MSB→LSB por byte) y los interpreta en LE.
    """
    header, pixels, w, h, bpp, row_size = leer_bmp(stego_path)
    carriers = indices_carrier(w, h, row_size)

    # 1) Leer los primeros 32 bits y convertirlos a 4 bytes (MSB→LSB por byte),
    #    luego interpretar esos bytes como little-endian ('<I').
    len_bits = [(pixels[carriers[i]] & 1) for i in range(32)]
    len_bytes = _bits_to_bytes_be(len_bits)
    msg_len = struct.unpack('<I', len_bytes)[0]

    # 2) Leer a continuación msg_len * 8 bits de mensaje
    total_bits = 32 + msg_len * 8
    if total_bits > len(carriers):
        raise ValueError("La longitud indicada excede la capacidad (archivo dañado o formato incorrecto).")

    msg_bits = [(pixels[carriers[i]] & 1) for i in range(32, total_bits)]
    out = _bits_to_bytes_be(msg_bits)
    return out.decode('utf-8')


# ----------------
# Métrica de PSNR
# ----------------
def calcular_psnr(original_path: str, stego_path: str) -> float:
    """
    PSNR calculado sobre bytes B,G,R (excluye padding).
    """
    _, pix_o, w, h, bpp, row_size = leer_bmp(original_path)
    _, pix_s, *_ = leer_bmp(stego_path)

    carriers = indices_carrier(w, h, row_size)
    mse = 0.0
    for idx in carriers:
        diff = int(pix_o[idx]) - int(pix_s[idx])
        mse += diff * diff
    mse /= len(carriers)

    if mse == 0:
        print("MSE=0 → PSNR=∞ (no hay diferencias).")
        return float('inf')

    psnr = 10.0 * math.log10((255 ** 2) / mse)
    print(f"MSE: {mse:.6f}")
    print(f"PSNR: {psnr:.2f} dB (≈ >40 dB suele ser imperceptible)")
    return psnr


# ---------------------------------
# (Opcional) Conversión a BMP 24 bpp
# ---------------------------------
def convertir_a_bmp_24bpp(entrada_path: str, salida_path: str = 'imagen.bmp'):
    """
    Convierte una imagen cualquiera (PNG, JPG, etc.) a BMP 24 bpp sin compresión.
    Requiere Pillow. Útil si no cuentas con un BMP 24 bpp de entrada.
    """
    try:
        from PIL import Image
        img = Image.open(entrada_path).convert('RGB')  # RGB → 24 bpp
        img.save(salida_path, format='BMP')
        print(f"Convertido '{entrada_path}' → '{salida_path}' (24 bpp).")
    except Exception as e:
        raise RuntimeError(f"No se pudo convertir '{entrada_path}' a BMP 24 bpp: {e}")


# ----------------
# Prueba
# ----------------
def ejecutar_practica1(
    src_path='/content/Images/volcan.bmp',
    dst_path='/content/Images/stego.bmp',
    mensaje='TELEMÁTICA SECRETA 2025'
):
    """
    - Usa 'Volcan.bmp' (24 bpp) como portada
    - Incrusta un mensaje, lo extrae y calcula PSNR
    """
    embed_lsb(src_path, dst_path, mensaje)
    recuperado = extract_lsb(dst_path)
    print("Recuperado:", recuperado)
    assert recuperado == mensaje, "¡Error en la extracción!"
    calcular_psnr(src_path, dst_path)
    print("Prueba exitosa.")

ejecutar_practica1()

"""# Generador de portadas y pruebas de capacidad"""

import math

def capacidad_max_bytes(width: int, height: int) -> int:
    cap_bits = abs(width) * abs(height) * 3
    cap_bits_utiles = cap_bits - 32  # restar 32 bits de la longitud
    if cap_bits_utiles < 0:
        return 0
    return cap_bits_utiles // 8

def ejecutar_prueba_capacidad(img_path: str, tamanos: list, umbral_psnr_db: float = 40.0):
    """
    Para cada tamaño de mensaje:
      - Inserta con embed_lsb()
      - Extrae y verifica
      - Calcula PSNR
      - Imprime fila con: (W×H), tamaño msg, PSNR, Imperceptible? (Sí/No)

    Requiere:
      - leer_bmp, indices_carrier, embed_lsb, extract_lsb, calcular_psnr
    """
    header, pixels, w, h, bpp, row_size = leer_bmp(img_path)
    cap_aprox = (abs(w)*abs(h)*3) // 8  # aprox, sin restar los 4 bytes
    cap_max = capacidad_max_bytes(w, h)  # exacto, descontando 4 bytes (32 bits)

    print(f"Imagen: {w}×{h} px | Capacidad máx. (bytes, con 1 LSB/canal) = {cap_max} (aprox: {cap_aprox})")
    print(f"{'Tamaño mensaje (bytes)':>22}  {'PSNR (dB)':>10}  {'¿Imperceptible?':>16}")

    resultados = []
    for n in tamanos:
        etiqueta = f"stego_{abs(w)}x{abs(h)}_{n}.bmp"
        try:
            msg = 'A' * n
            embed_lsb(img_path, etiqueta, msg)
            rec = extract_lsb(etiqueta)
            assert rec == msg, "¡Error: extracción no coincide!"

            psnr = calcular_psnr(img_path, etiqueta)
            imperc = "Sí" if (psnr == float('inf') or psnr >= umbral_psnr_db) else "No"
            print(f"{n:>22}  {psnr:>10.2f}  {imperc:>16}")
            resultados.append((f"{abs(w)}×{abs(h)}", n, psnr, imperc))
        except Exception as e:
            print(f"{n:>22}  {'—':>10}  {'ERROR':>16}  -> {e}")
            resultados.append((f"{abs(w)}×{abs(h)}", n, None, f"ERROR: {e}"))

    return resultados, cap_max

def prueba_capacidad_max(img_path: str, umbral_psnr_db: float = 40.0):
    """
    Inserta un mensaje del tamaño máximo y mide PSNR.
    """
    header, pixels, w, h, bpp, row_size = leer_bmp(img_path)
    cap_max = capacidad_max_bytes(w, h)
    etiqueta = f"stego_{abs(w)}x{abs(h)}_capMax.bmp"

    print(f"Imagen: {w}×{h} px | Capacidad máxima exacta (bytes) = {cap_max}")
    try:
        msg = 'A' * cap_max
        embed_lsb(img_path, etiqueta, msg)
        rec = extract_lsb(etiqueta)
        assert rec == msg, "¡Error: extracción no coincide!"
        psnr = calcular_psnr(img_path, etiqueta)
        imperc = "Sí" if (psnr == float('inf') or psnr >= umbral_psnr_db) else "No"
        print(f"{'Capacidad máx.':>22}  {psnr:>10.2f}  {imperc:>16}")
        return (f"{abs(w)}×{abs(h)}", cap_max, psnr, imperc)
    except Exception as e:
        print(f"{'Capacidad máx.':>22}  {'—':>10}  {'ERROR':>16}  -> {e}")
        return (f"{abs(w)}×{abs(h)}", cap_max, None, f"ERROR: {e}")

# ----------------
# GENERADOR DE PORTADAS DISTINTOS TAMAÑOS
# ----------------
def generar_bmp_sintetica(path='imagen.bmp', w=512, h=512):
    import numpy as np
    from PIL import Image
    arr = np.zeros((h, w, 3), dtype=np.uint8)
    for y in range(h):
        for x in range(w):
            arr[y, x] = (x % 256, y % 256, (x+y) % 256)  # gradiente simple
    Image.fromarray(arr, 'RGB').save(path, format='BMP')
    print(f"Generada '{path}' {w}x{h} (24 bpp).")

# Genera 200×200 y 512×512:
generar_bmp_sintetica('/content/Images/img_200x200.bmp', 200, 200)
generar_bmp_sintetica('/content/Images/img_512x512.bmp', 512, 512)

"""## Experimento de capacidad"""

# 200×200, mensajes de 50 y 500 bytes
res_200, cap_200 = ejecutar_prueba_capacidad('/content/Images/img_200x200.bmp', [50, 500])

# 512×512, mensaje de 5,000 bytes
res_512, cap_512 = ejecutar_prueba_capacidad('/content/Images/img_512x512.bmp', [5000])

# 512×512, capacidad máxima exacta
res_max_512 = prueba_capacidad_max('/content/Images/img_512x512.bmp')

"""# Generador de Histogramas."""

import numpy as np
import matplotlib.pyplot as plt

def mostrar_histograma_bgr(original_path: str, stego_path: str):
    _, p0, w, h, bpp, row_size = leer_bmp(original_path)
    _, p1, *_ = leer_bmp(stego_path)
    carriers = indices_carrier(w, h, row_size)

    # Separar canales
    b0 = np.array([p0[i] for i in carriers[0::3]])
    g0 = np.array([p0[i] for i in carriers[1::3]])
    r0 = np.array([p0[i] for i in carriers[2::3]])

    b1 = np.array([p1[i] for i in carriers[0::3]])
    g1 = np.array([p1[i] for i in carriers[1::3]])
    r1 = np.array([p1[i] for i in carriers[2::3]])

    fig, axs = plt.subplots(3, 2, figsize=(10, 8))
    canales = [('B', b0, b1), ('G', g0, g1), ('R', r0, r1)]

    for row, (name, o, s) in enumerate(canales):
        axs[row, 0].hist(o, bins=256, range=(0,255), color=name.lower())
        axs[row, 0].set_title(f'Original {name}')

        axs[row, 1].hist(s, bins=256, range=(0,255), color=name.lower())
        axs[row, 1].set_title(f'Stego {name}')

    plt.tight_layout()
    plt.show()

mostrar_histograma_bgr('/content/Images/volcan.bmp', '/content/Images/stego.bmp')