# -*- coding: utf-8 -*-
"""Practica_MetaDataMP3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Czwt9o8dk3Bbz1Ue-6xZ0cy0hRw7wbnc
"""

!pip install mutagen

os = __import__('os')
from mutagen.id3 import ID3, TIT2, TPE1, TALB, APIC, ID3NoHeaderError
from mutagen.mp3 import MP3

# Ruta de tu archivo
file_path = "/content/MP3/Love.mp3.mpeg"


# --- 1. CARGAR O CREAR ETIQUETAS SEGURAMENTE ---
try:
    audio = MP3(file_path, ID3=ID3)
except ID3NoHeaderError:
    print("El archivo no tiene etiquetas ID3. Creando contenedor nuevo...")
    audio = MP3(file_path)
    audio.add_tags()

# --- 2. MODIFICAR METADATOS ---
audio.tags.add(TIT2(encoding=3, text="Amor"))
audio.tags.add(TPE1(encoding=3, text="León Larregui"))
audio.tags.add(TALB(encoding=3, text="Unplugged"))
audio.save()
print("¡Metadatos actualizados con éxito!")

# --- 3. LEER Y MOSTRAR METADATOS ---
duration = audio.info.length
tags = audio.tags

title = tags.get('TIT2', 'Desconocido').text[0] if 'TIT2' in tags else 'Desconocido'
artist = tags.get('TPE1', 'Desconocido').text[0] if 'TPE1' in tags else 'Desconocido'
album = tags.get('TALB', 'Desconocido').text[0] if 'TALB' in tags else 'Desconocido'

print(f"\n--- INFORMACIÓN ACTUALIZADA ---")
print(f"Título: {title}")
print(f"Artista: {artist}")
print(f"Álbum: {album}")
print(f"Duración: {duration:.2f} segundos")

# --- 4. EXTRAER CARÁTULA (SI EXISTE) ---
art_extracted = False
for tag in audio.tags.values():
    if isinstance(tag, APIC):
        with open("album_art.jpg", "wb") as img_file:
            img_file.write(tag.data)
        print("¡Carátula extraída con éxito como 'album_art.jpg'!")
        art_extracted = True
        break

if not art_extracted:
    print("El archivo no contiene ninguna imagen de carátula (APIC).")